# Square Custom API Documentation

## Base URL
@baseUrl = http://localhost:8001/api

### Fetch Locations
GET {{baseUrl}}/locations HTTP/1.1

### Fetch Catalog Objects
GET {{baseUrl}}/catalog/objects HTTP/1.1

### Fetch Catalog Objects by Type (e.g., CATEGORY, CUSTOM_ATTRIBUTE_DEFINITION)
GET {{baseUrl}}/catalog/objects?type=ITEM HTTP/1.1

### Fetch Catalog ItemsAndImages by Categories (e.g., CoffeeBean)
GET {{baseUrl}}/catalog/items?category=CoffeeBean HTTP/1.1

### Fetch Orders by Status (e.g., OPEN, COMPLETED)
GET {{baseUrl}}/orders?status=OPEN HTTP/1.1

### Create Order
POST {{baseUrl}}/orders HTTP/1.1
Content-Type: application/json

{
  "items": [
    {
      "itemId": "R6V4JQNCKY5XLYBIJIKTB5LB",
      "itemVarId": "QKF5UACTISTHEDNSRH77MWIQ",
      "itemQuantity": 50
    },
    {
      "itemId": "E2U3QSQ77QWJD6PB2SUZ3EC3",
      "itemVarId": "VOV4T24BSNMYZALO4URAFOOB",
      "itemQuantity": 100
    },
    {
      "itemId": "FK5RZ7OF5CEIXOP4VKYSF3WU",
      "itemVarId": "KML46F6KYBPZCUTVPJEUGC2V",
      "itemQuantity": 50
    },
    {
      "itemId": "4HIWZDZ657I2BLGK324SSWOE",
      "itemVarId": "PK4BZABE4TQG6TZGOPVEWUIF",
      "itemQuantity": 50
    },
    {
      "itemId": "RPUKACTMQCJ4IBBLWQVFJ3UL",
      "itemVarId": "HHDBEQQMGSVLWYSKBN4ZJOVA",
      "itemQuantity": 50
    }
  ],
  "note": "This is a sample order for a selection of premium coffee beans. The order includes 50 grams of Blue Mountain coffee, 150 grams of Colombia coffee, and 100 grams of Hawaii Kona coffee. Each coffee bean variety offers a unique flavor profile and is carefully roasted to perfection. This order is perfect for coffee enthusiasts looking to explore different tastes and indulge in the finest quality beans. Enjoy the rich aroma and smooth flavors of these exceptional coffees!"
}


### Cancel Order
PUT {{baseUrl}}/orders/qt1eXz6lo5OOyfEFHYzXZzZvWmEZY/cancel HTTP/1.1
Content-Type: application/json

### Fetch Payments by Status (e.g., PENDING, COMPLETED)
GET {{baseUrl}}/payments?status=COMPLETED HTTP/1.1

### Create Payment with Cash
POST {{baseUrl}}/payments HTTP/1.1
Content-Type: application/json

{
  "orderId": "qt1eXz6lo5OOyfEFHYzXZzZvWmEZY",
  "token": "CASH",
  "buyerSuppliedAmount": 10000,
}

### Create Payment with Card
POST {{baseUrl}}/payments HTTP/1.1
Content-Type: application/json

{
  "orderId": "SJ1k7fP1j06gAM3XV0PK1hbnMWQZY",
  "token": "cnon:card-nonce-ok"
}

### Create Terminal Checkout
POST {{baseUrl}}/terminal/checkout HTTP/1.1
Content-Type: application/json

{
  "orderId": "a6S7trSXLQbctyP6ZBNFmAtQac4F",
  "amount": "2441"
}
